services:
  - type: web
    name: password-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host=0.0.0.0 --port=${PORT}"
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
